# Generated by Django 5.0.2 on 2025-02-26 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('serving_qty', models.FloatField()),
                ('serving_unit', models.CharField(max_length=50)),
                ('nf_calories', models.FloatField()),
                ('nf_protein', models.FloatField(blank=True, null=True)),
                ('nf_total_carbohydrate', models.FloatField(blank=True, null=True)),
                ('nf_total_fat', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='counter.category')),
            ],
            options={
                'ordering': ['food_name'],
            },
        ),
    ]
