# Generated by Django 5.0.2 on 2025-02-26 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_alter_category_options_fooditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fooditem',
            options={},
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='nf_calories',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='nf_protein',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='nf_total_carbohydrate',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='nf_total_fat',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='serving_qty',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='serving_unit',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='counter.category'),
        ),
    ]
