# Generated by Django 5.0.2 on 2025-02-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_alter_category_options_alter_fooditem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='serving_size',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='nf_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='nf_protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='nf_total_carbohydrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='nf_total_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_qty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_unit',
            field=models.CharField(default='serving', max_length=50),
        ),
    ]
